mongo:
    image: mongo
    restart: always
    volumes:
        - "/data/db:/data/db"
    ports:
        - "27017:27017"
node:
    build: ./node
    restart: always
    volumes:
        - "/pasta/do/projeto/app:/usr/src/app"
    links:
        - "mongo:mongo"
    ports:
        - "3000:3000"
